services:
  postgres:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: repeater_atlas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # This is normally not used, just for debugging the docker image built locally
  repeater-atlas:
    image: repeater-atlas:latest
    environment:
      DATABASE_URL: postgres://repeater_atlas:repeater_atlas@postgres/repeater_atlas
      RUST_LOG: debug
    ports:
      - "3001:3000"
    restart: no

  # This is normally not used, just for debugging the docker image built by GitHub
  repeater-atlas-gh:
    image: ghcr.io/trygvis/repeater-atlas:main
    environment:
      DATABASE_URL: postgres://repeater_atlas:repeater_atlas@postgres/repeater_atlas
      RUST_LOG: debug
    ports:
      - "3002:3000"
    restart: no

  agent:
    profiles:
      - agent
    build:
      context: ./
      dockerfile_inline: |
        FROM debian:trixie
        RUN apt-get update && apt-get install --no-install-recommends --yes \
          bash-completion \
          ca-certificates \
          curl \
          direnv \
          git \
          less \
          man \
          postgresql-client \
          ripgrep \
          rustup \
          sudo \
          vim \
          wget \
          zstd \
          ;

        COPY bin/codex /usr/local/bin/
        # This downloads codex
        RUN codex --version
        RUN echo ". <(codex completion)" > /etc/bash_completion.d/codex
        RUN echo ". <(direnv hook bash)" > /etc/profile.d/direnv.sh
        # RUN echo "echo DIRENV!!" > /etc/profile.d/direnv

        COPY bin/agent-shell /usr/bin/agent-shell
        CMD /usr/bin/agent-shell
    volumes:
      - home:/home
      - ./workspaces:/workspaces
      - ./.git:/git:ro

volumes:
  postgres_data:
  home:
