// =============================================================================
// Repeater Atlas — Logbook PDF
// Generated by the web service. To render standalone, run:
//   typst compile logbook.typ logbook.pdf
// =============================================================================

#let title-page(call_sign: "") = {
  page(header: none, footer: none)[
    #align(center + horizon)[
      #text(size: 28pt, weight: "bold")[Portable Logbook for #call_sign]
    ]
  ]
}

#let log-pages(call_sign: "", paper: "a4", log_pages: 10) = {
  set text(size: 16pt)
  let row-height = 1.2cm
  let header-height = 0.7cm
  let page-margin = 1cm
  let band-height = 1.5cm

  let col_widths = (1.5fr, 3fr, 2fr, 2fr, 2fr, 2.5fr, 2.5fr, 2fr)
  let col_names = ("QSO #", "Station", "Time", "RST Sent", "RST Rcvd", "Freq", "Mode", "Power")
  let ncols = col_names.len()

  // Landscape: A4 short edge = 210mm, A5 short edge = 148mm.
  // Margins carve out space from the paper edge; header/footer bands then
  // consume space from within the content area. Table header adds header-height.
  let page-short-edge = if paper == "a5" { 148mm } else { 210mm }
  let usable = page-short-edge - 2 * (band-height + page-margin) - header-height
  let entries_per_page = int(usable / (2 * row-height))

  let log-table = table(
    columns: col_widths,
    rows: (auto, row-height),
    align: top,
    table.header(..col_names.map(n => table.cell(fill: none)[*#n*])),
    ..range(entries_per_page).map(_ => (
      ..range(ncols).map(_ => []),
      table.cell(colspan: ncols, align: left + horizon)[Remarks:],
    )).flatten(),
  )

  set page(
    margin: (x: page-margin, y: band-height + page-margin),
    header: block(height: band-height, width: 100%, align(bottom + left,
      [#h(1fr) Date: #box(width: 6cm, line(length: 100%)) #h(1fr) Location: #box(width: 6cm, line(length: 100%)) #h(1fr)],
    )),
    footer: block(height: band-height, width: 100%, align(top,
      [#call_sign #h(1fr) Page: #context counter(page).display()],
    )),
  )
  for i in range(log_pages) {
    if i > 0 { pagebreak() }
    align(center + horizon, log-table)
  }
}

#let phonetic-alphabet() = {
  let phonetics = (
    ("A", "Alpha"),   ("B", "Bravo"),   ("C", "Charlie"), ("D", "Delta"),
    ("E", "Echo"),    ("F", "Foxtrot"), ("G", "Golf"),    ("H", "Hotel"),
    ("I", "India"),   ("J", "Juliet"),  ("K", "Kilo"),    ("L", "Lima"),
    ("M", "Mike"),    ("N", "November"),("O", "Oscar"),   ("P", "Papa"),
    ("Q", "Quebec"),  ("R", "Romeo"),   ("S", "Sierra"),  ("T", "Tango"),
    ("U", "Uniform"), ("V", "Victor"),  ("W", "Whiskey"), ("X", "X-ray"),
    ("Y", "Yankee"),  ("Z", "Zulu"),
  )
  [= Phonetic Alphabet]
  align(center, grid(
      columns: (1cm, 3cm) * 6,
      column-gutter: (0cm, 1cm) * 6,
      row-gutter: 0.3cm,
      ..phonetics.map(((l, w)) => (
        align(center)[*#l*],
        align(left)[#w],
      )).flatten(),
  ))
}

#let locations-page(locations: ()) = {
  [
    = Locations
    #if locations.len() == 0 [
      _No locations registered._
    ] else [
      #table(
        columns: (auto, auto, auto),
        table.cell(fill: none)[*Address*],
        table.cell(fill: none)[*Maidenhead*],
        table.cell(fill: none)[*Lat / Lon*],
        ..locations.map(loc => (
          [#loc.at("address", default: "")],
          [#loc.at("maidenhead", default: "")],
          [#loc.at("latlon", default: "")],
        )).flatten(),
      )
    ]
  ]
}

#let frequency-bands() = {
  // Format a frequency given in MHz. Values >= 1000 MHz are shown in GHz.
  // Uses narrow no-break space as thousands separator.
  let fmt-freq(mhz) = {
    let unit = if mhz >= 1000.0 { "GHz" } else { "MHz" }
    let val = if mhz >= 1000.0 { mhz / 1000.0 } else { mhz }
    let s = str(val)
    let parts = s.split(".")
    let int-part = parts.at(0)
    let dec-part = if parts.len() > 1 { "." + parts.at(1) } else { "" }
    // Insert narrow no-break space (U+202F) as thousands separator
    let n = int-part.len()
    let grouped = if n > 3 { int-part.slice(0, n - 3) + "\u{202F}" + int-part.slice(n - 3) } else { int-part }
    [#grouped#dec-part #unit]
  }

  // Each band: (name, start-MHz, end-MHz, modes)
  // Each mode: (name, start-MHz, end-MHz)
  // Source: IARU Region 1 HF Band Plan, effective 2016-06-01
  let bands = (
    ("160 m", 1.810, 2.000, (
      ("CW",        1.810, 1.838),
      ("Digimodes", 1.838, 1.840),
      ("All modes", 1.840, 2.000),
    )),
    ("80 m", 3.500, 3.800, (
      ("CW",        3.500, 3.570),
      ("Digimodes", 3.570, 3.600),
      ("All modes", 3.600, 3.800),
    )),
    ("60 m", 5.3515, 5.3665, (
      ("CW / Narrow band", 5.3515, 5.3540),
      ("All modes",        5.3540, 5.3660),
      ("Narrow band",      5.3660, 5.3665),
    )),
    ("40 m", 7.000, 7.200, (
      ("CW",        7.000, 7.040),
      ("Digimodes", 7.040, 7.053),
      ("All modes", 7.053, 7.200),
    )),
    ("30 m", 10.100, 10.150, (
      ("CW",        10.100, 10.130),
      ("Digimodes", 10.130, 10.150),
    )),
    ("20 m", 14.000, 14.350, (
      ("CW",        14.000, 14.070),
      ("Digimodes", 14.070, 14.099),
      ("Beacons",   14.099, 14.101),
      ("All modes", 14.101, 14.350),
    )),
    ("17 m", 18.068, 18.168, (
      ("CW",        18.068, 18.095),
      ("Digimodes", 18.095, 18.109),
      ("Beacons",   18.109, 18.111),
      ("All modes", 18.111, 18.168),
    )),
    ("15 m", 21.000, 21.450, (
      ("CW",              21.000, 21.070),
      ("Digimodes",       21.070, 21.110),
      ("All modes",       21.110, 21.120),
      ("Digimodes",       21.120, 21.149),
      ("Beacons",         21.149, 21.151),
      ("All modes",       21.151, 21.450),
    )),
    ("12 m", 24.890, 24.990, (
      ("CW",        24.890, 24.915),
      ("Digimodes", 24.915, 24.929),
      ("Beacons",   24.929, 24.931),
      ("All modes", 24.931, 24.990),
    )),
    ("10 m", 28.000, 29.700, (
      ("CW",             28.000, 28.070),
      ("Digimodes",      28.070, 28.190),
      ("Beacons",        28.190, 28.225),
      ("All modes",      28.225, 29.000),
      ("All modes",      29.000, 29.300),
      ("Satellite",      29.300, 29.520),
      ("FM / Repeaters", 29.520, 29.700),
    )),
    ("6 m", 50.000, 52.000, (
      ("CW",        50.000, 50.100),
      ("Voice",     50.100, 50.300),
      ("Digimodes", 50.300, 50.400),
      ("Digimodes", 50.500, 51.210),
      ("Voice",     51.410, 51.590),
    )),
    ("2 m", 144.000, 146.000, (
      ("CW",        144.025, 144.165),
      ("Voice",     144.165, 144.400),
      ("Digimodes", 144.500, 144.963),
      ("Voice",     145.206, 145.563),
    )),
    ("70 cm", 432.000, 438.000, (
      ("CW",        432.000, 432.100),
      ("Voice",     432.100, 432.400),
      ("Digimodes", 432.500, 432.600),
      ("Voice",     433.225, 433.600),
      ("Digimodes", 433.600, 434.600),
    )),
  )

  [
    = Frequency Bands

    _IARU Region 1 / Europe_

    #let band-table = table(
      columns: (auto, auto, auto),
      table.cell(fill: none)[*Band / Mode*],
      table.cell(fill: none)[*Start*],
      table.cell(fill: none)[*End*],
      ..bands.map(((band, start, end, modes)) => (
        (table.cell[*#band*], table.cell[*#fmt-freq(start)*], table.cell[*#fmt-freq(end)*]),
        ..modes.map(((mode, ms, me)) => (
          table.cell(inset: (left: 1em))[#mode], fmt-freq(ms), fmt-freq(me),
        )),
      )).flatten(),
    )

    #columns(2, band-table)
  ]
}

#let logbook(
  call_sign: "N0CALL",
  paper: "a4",
  log_pages: 10,
  title_page: true,
  phonetic_page: true,
  bands_page: true,
  locations_page: true,
  locations: (),
) = {
  set page(paper: paper, flipped: true, margin: 1cm)
  set text(size: 12pt, font: "DejaVu Sans")

  if title_page { title-page(call_sign: call_sign) }
  log-pages(call_sign: call_sign, paper: paper, log_pages: log_pages)

  let has_references = phonetic_page or locations_page or bands_page
  if has_references {
    [= References]
  }
  if phonetic_page {
    phonetic-alphabet()
  }
  if locations_page {
    locations-page(locations: locations)
  }
  if bands_page {
    frequency-bands()
  }
}

// =============================================================================
// Invocation
// =============================================================================

#logbook(
  call_sign: "{{ call_sign }}",
  paper: "{{ paper }}",
  log_pages: {{ log_pages }},
  title_page: {{ title_page }},
  phonetic_page: {{ phonetic_page }},
  bands_page: {{ bands_page }},
  locations_page: {{ locations_page }},
  locations: (
{%- for loc in locations %}
    (address: "{{ loc.address }}", maidenhead: "{{ loc.maidenhead }}", latlon: "{{ loc.latlon }}"),
{%- endfor %}
  ),
)
