DROP TABLE repeater_service_dmr_talkgroup;
DROP TABLE repeater_service;
DROP TABLE repeater_system;

DROP TYPE SSB_SIDEBAND;
DROP TYPE APRS_MODE;
DROP TYPE DSTAR_MODE;
DROP TYPE TONE_KIND;
DROP TYPE FM_BANDWIDTH;
DROP TYPE REPEATER_SERVICE_KIND;
